version: '3'

services:
  # NOTE: DONT FORGET TO START SERVICE : sudo service docker start
  database:
    # network_mode: bridge
    tty: true
    container_name: Test_Code_GammaSoft_Db_ng
    # Image: https://hub.docker.com/_/mysql
    image: mysql:${MYSQL_VERSION:-8.0}
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
      # Autres variables d'environement possibles :
      MYSQL_DATABASE: ${MYSQL_DATABASE:-test_code_gammasoft_ng}
      # MYSQL_USER: ${MYSQL_USER:-symfony}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # ...
    volumes:
      - data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    links:
      - database
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
  backend:
    # network_mode: bridge
    tty: true
    container_name: Test_Code_GammaSoft_back_ng
    image: testproject/gammasoft_ng/back:dev
    build:
      context: ./
      dockerfile: .docker/Dockerfile.Symfony
    command:
      [
        "bash",
        "-c",
        "symfony --no-interaction server:stop; symfony --no-interaction server:start"
      ]
    ports:
      - "8001:8000"
    volumes:
      - ./back:/var/www/default
    environment:
      ENV_VAR: "value"
  frontend:
    container_name: Test_Code_GammaSoft_front_ng
    image: testproject/gammasoft_ng/front:dev
    build:
      context: ./
      dockerfile: .docker/Dockerfile.Angular
    command: serve --open --host 0.0.0.0
    ports:
      - "4201:4200"
    volumes:
      - ./front:/home/node/app
    stdin_open: true
    environment:
      - 'EXTEND_ESLINT=true'

volumes:
  data:
    name: data_mysql
