FROM node:20-alpine

LABEL maintainer="maxime.bourdin.tic@gmail.com"

RUN apk add --no-cache git alpine-sdk bash tzdata

RUN mkdir /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

ENV HOME=/home/node

ENV TZ Europe/Paris

WORKDIR $HOME/app

RUN npm i -g npm

RUN npm install -g @angular/cli --save-dev && npm cache clean --force

EXPOSE 4200

ENTRYPOINT ["ng"]